### PR TITLE
osm now use only oauth2

### PR DESCRIPTION
**Pull request by Darkham42**
As notified in #312 osm deprecated Oauth 1.0,  there is few modifications to be able to use PDM again.

- Update sendfile_osm_oauth_protector submodule
- Update osm-auth
- Update osm-request

### CODE REVIEW

**Comment by PanierAvide** [comment]
So I tested it and made minor changes:
- Renamed API_OSM_URL into OSM_API_URL for more coherence
- Fixed osm-auth import client-side
- Changed redirect_uri to always match homepage, as OSM Oauth2 registering form doesn't allow patterns to match any page of the site ?

**Comment by flacombe** [comment]
Hello and thank you @Darkham42 

I've deployed it over Enedis instance but when I click on "Authorize" on OSM website, it comes back to PDM but without authentication at all.

I still get the "sign in" button without my name on it.
image

Is there any issue?

**Comment by PanierAvide** [comment]
Hmm that's weird because I had it working on my side, is your instance registered as an OAuth 2 app ? Here's the conf I used for projetdumois.fr :

image

**Comment by flacombe** [comment]
Thank you.
It actually work by unselecting "Application confidentielle".
There may be some bug on their side?

So its ok for me, go!

image

**Comment by PanierAvide** [comment]
Thanks @Darkham42 for the fix and @flacombe for the live test :grin:

**Pull request merged**
